### ISSUE TITLE
KV Sessions: Cannot read properties of undefined (reading 'deleteData')

### ISSUE THREAD

**Issue by depsimon** [vercel/remix#117]
I've been setting up KV Sessions in my Remix project hosted on Vercel and sometimes I get this error when not authenticated (new, empty session).

The behavior I identified so far:

- on first ever render (no session): it renders /auth/login + commits the session (empty).
- when refreshing the page: it still renders /auth/login + commits the session (still empty) and throws the error.

```
TypeError: Cannot read properties of undefined (reading 'deleteData')
    at updateData (/Users/simon/Code/project/node_modules/.pnpm/@vercel+remix@2.9.2-patch.2_@remix-run+dev@2.9.2_@remix-run+react@2.9.2_react-dom@18.3.1_reac_j53m4mtx7ywlsddwhgupie4rvq/node_modules/@vercel/remix/dist/sessions.js:51:23)
    at Module.commitSession (/Users/simon/Code/project/node_modules/.pnpm/@remix-run+server-runtime@2.9.2_typescript@5.4.5/node_modules/@remix-run/server-runtime/dist/sessions.js:129:15)
    at loader (/Users/simon/Code/project/apps/project/app/routes/auth.login.tsx:50:29)
```

The content of my session data is `{}` so we end up in [this if case](https://github.com/vercel/remix/blob/f858a16f57a1e9da481840a0615f87df5fd8cc28/packages/vercel-remix/sessions.ts#L72).

It seems that in some case that `this` is undefined at that point.

I tried updating the code of @vercel/remix to use `await kv.del(id)` instead of `this.deleteData(id)`, and that works, I'm not sure if that's a suitable fix though.

I've read through multiple sessions implementations, and it seems that none of the use `this`.

I can share a Vercel project in DMs if it can help identifying the issue.

**Comment by TooTallNate** [comment]
Thanks for the report and thorough investigation. This is fixed in https://github.com/vercel/remix/pull/119.
