### ISSUE TITLE
Vercel build fails for remix v2-pre apps

### ISSUE THREAD

**Issue by jxe** [vercel/remix#53]
To reproduce, see

https://github.com/remix-run/remix/issues/7350#issuecomment-1710339449

Errors look like

```
✘ [ERROR] Could not resolve "node:crypto"
--
12:47:50.104 |  
12:47:50.104 | node_modules/@remix-run/node/dist/sessions/fileStorage.js:15:21:
12:47:50.104 | 15 │ var crypto = require('node:crypto');
12:47:50.104 | ╵                      ~~~~~~~~~~~~~
12:47:50.104 |  
12:47:50.105 | The package "node:crypto" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
```

**Comment by cb1kenobi** [comment]
Thanks for reporting the issue. I'll take a look as soon as possible.

**Comment by cb1kenobi** [comment]
Yeah, looks like there are issues. When I test an app using Remix v2.0.0-pre.11, I get:

```
TypeError: import_node.Response is not a constructor
    at onShellReady (/Users/chris/code/sites/remixfun3/app/entry.server.tsx:110:13)
    at finishedTask (/Users/chris/code/sites/remixfun3/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6513:7)
    at retryTask (/Users/chris/code/sites/remixfun3/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6598:5)
    at performWork (/Users/chris/code/sites/remixfun3/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6642:7)
    at Immediate._onImmediate (/Users/chris/code/sites/remixfun3/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.node.development.js:6969:12)
    at processImmediate (node:internal/timers:476:21)
```

I'll create a ticket so we can prioritize this issue. Thanks!

**Comment by Sandy-Garrido** [comment]
Awesome, I just found this side of vercel. Came from the main Vercel repo after I realised the Vercel build steps include installing an earlier version of remix dev (1.15.x).

**Comment by TooTallNate** [comment]
Remix v2 is now supported. Please try deploying again after updating your Remix-related dependencies to v2.0.0 or newer.
