### ISSUE TITLE
TypeError: nodeResponse.headers.raw is not a function at sendRemixResponse

### ISSUE THREAD

**Issue by tsuki-lab** [vercel/remix#76]
Hello, I am using `@vercel/og` with Remix and deploying to Vercel.
I found an error in the production environment and am reporting it.

```
TypeError: nodeResponse.headers.raw is not a function
    at sendRemixResponse (file:///var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs:58:48)
    at Server.default (file:///var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs:75:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (/var/task/___vc/__launcher/bridge-server-72TT5FOD.js:1:8478)
```

This error seems to be the behavior as reported in https://github.com/remix-run/remix/issues/4354.

**Comment by wong2** [comment]
I'm getting this with `vercel/ai`

**Comment by TooTallNate** [comment]
Can you share an example repo that demonstrates the issue?
