### ISSUE TITLE
Unhandled Promise Rejection when using node-fetch, Shopify remix app with shopify api v9 deployed to vercel

### ISSUE THREAD

**Issue by anhdd-kuro** [vercel/remix#77]
I am currently working on a Shopify custom app built with the Remix template and deployed on Vercel. Initially, it ran smoothly with Remix version 2.5.1 and Shopify API version 8.1. However, upon updating to [Shopify API version 9](https://github.com/Shopify/shopify-api-js/blob/main/packages/shopify-api/docs/migrating-to-v9.md#migrating-to-v9), the application started crashing when making any API calls using the fetch API. Below is the detailed log:

```
Unhandled Promise Rejection 
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError: First parameter has member 'readable' that is not a ReadableStream.",
"reason":
{"errorType":"TypeError","errorMessage":
"First parameter has member 'readable' that is not a ReadableStream.",
"stack":["TypeError: First parameter has member 'readable' that is not a ReadableStream.","   
 at assertReadableStream (/var/task/node_modules/.pnpm/web-streams-polyfill@3.3.2/node_modules/web-streams-polyfill/dist/ponyfill.js:466:19)","    
at convertReadableWritablePair (/var/task/node_modules/.pnpm/web-streams-polyfill@3.3.2/node_modules/web-streams-polyfill/dist/ponyfill.js:4038:9)","    
at ReadableStream.pipeThrough (/var/task/node_modules/.pnpm/web-streams-polyfill@3.3.2/node_modules/web-streams-polyfill/dist/ponyfill.js:4122:29)","    
at fetchFinale (node:internal/deps/undici/undici:9584:56)","    
at mainFetch (node:internal/deps/undici/undici:9476:9)","    
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError: First parameter has member 'readable' that is not a ReadableStream.","    
at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)","    
at process.emit (node:events:529:35)","    
at emit (node:internal/process/promises:149:20)","    
at processPromiseRejections (node:internal/process/promises:283:27)","    
at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"]}
```

here is the dependencies

```json
  "dependencies": {
    "@prisma/client": "5.7.1",
    "@remix-run/css-bundle": "^2.5.0",
    "@remix-run/dev": "2.5.1",
    "@remix-run/node": "2.5.1",
    "@remix-run/react": "2.5.1",
    "@remix-run/serve": "2.5.1",
    "@shopify/app": "3.53.1",
    "@shopify/cli": "3.53.1",
    "@shopify/polaris": "12.10.0",
    "@shopify/polaris-icons": "^8.0.0",
    "@shopify/shopify-api": "9.0.2",
    "@shopify/shopify-app-remix": "2.2.0",
    "@shopify/shopify-app-session-storage-prisma": "2.0.3",
    "@vercel/remix": "2.5.1",
    "isbot": "4.4.0",
    "prisma": "5.7.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-phone-number-input": "3.3.9",
    "remix-utils": "7.5.0",
    "usehooks-ts": "2.9.5"
  },
```

Please assist in identifying and resolving this issue. Thank you.

**Comment by apalumbo** [comment]
@anhdd-kuro did you find a way to handle the issue

**Comment by anhdd-kuro** [comment]
@apalumbo 
I did get response from vercel but look like we have to figure it out our self
https://github.com/vercel/vercel/issues/11069

**Comment by anhdd-kuro** [comment]
Oh , I'v got [response](https://github.com/Shopify/shopify-app-template-remix/issues/530) from remix team
